name: outdoor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: SofiaProRegular
      fonts:
        - asset: fonts/SofiaProRegular.ttf
    - family: SofiaProMedium
      fonts:
        - asset: fonts/SofiaProMedium.ttf
    - family: SofiaProSemiBold
      fonts:
        - asset: fonts/SofiaProSemiBold.ttf
    - family: SofiaProLight
      fonts:
        - asset: fonts/SofiaProLight.ttf
    - family: SofiaProBold
      fonts:
        - asset: fonts/SofiaProBold.ttf
    - family: Helveticaneue
      fonts:
        - asset: fonts/Helveticaneue.ttf

