name: outdoor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  logger: ^2.0.2+1
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.8
  cached_network_image: ^3.3.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

# flutter_native_splash:
#   android: true
#   ios: true
#   web: false
#   image: assets/images/travelo.png
#   background_image: "assets/images/travelo_bg.png"

#   android_12:
#     image: assets/images/travelo.png
#     background_image: "assets/images/travelo_bg.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/SofiaProBold.ttf
          weight: 700
        - asset: assets/fonts/SofiaProSemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaProMedium.ttf
          weight: 500
        - asset: assets/fonts/SofiaProRegular.ttf
          weight: 400
        - asset: assets/fonts/SofiaProLight.ttf
          weight: 300
    - family: Helveticaneue
      fonts:
        - asset: assets/fonts/Helveticaneue.ttf
